name: 'build'

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  nix-curses:
    name: nix curses
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: nix build
      run: nix build -L .#

  nix-dev-tools:
    name: nix dev-tools
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: nix build
      run: nix build -L .#dev-tools

  curses:
    name: curses
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #   args: '--target aarch64-apple-darwin'
          # - platform: 'macos-latest' # for Intel based macs.
          #   args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev libvulkan-dev
 
      - name: Install Vulkan SDK and Runtime
        uses: jakoch/install-vulkan-sdk-action@v1.2.3
        with:
          vulkan_version: 1.4.313.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm' # Set this to npm, yarn or pnpm.

      - uses: SebRollen/toml-action@v1.0.1
        id: version
        with:
          file: 'Cargo.toml'
          field: 'workspace.package.version'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: pnpm i --frozen-lockfile # change this to npm or pnpm depending on which one you use.

      - name: Build Tauri app
        id: tauri-artifacts
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ startsWith(github.ref, 'refs/heads/releases/') && (endsWith(github.ref, '-pre') && 'v__VERSION__-pre' || 'v__VERSION__') || null }}  # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: ${{ startsWith(github.ref, 'refs/heads/releases/') && (endsWith(github.ref, '-pre') && 'curses-v__VERSION__-pre' || 'curses-v__VERSION__' ) || null }}
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: ${{ startsWith(github.ref, 'refs/heads/releases/') && endsWith(github.ref, '-pre')}}
          # Use different tauri config if prerelease (msi bundles only support x.x.x versioning)
          args: "${{ matrix.args }} --config .github/workflows/configs/Tauri.build${{ endsWith(steps.version.outputs.value, '-pre') && '-pre' || null }}.toml"
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: target/release/bundle/appimage/curses_${{steps.version.outputs.value}}_amd64.AppImage
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsEXE
          path: target/release/curses.exe
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsInstaller
          path: target/release/bundle/msi/curses_${{steps.version.outputs.value}}_x64_en-US.msi
