name: 'check'

on:
  workflow_dispatch: {}
  push:
    branches:
      - dev
      - master
      - 'releases/**'
  pull_request:
    branches:
      - dev
      - master
      - 'releases/**'

jobs:
  flake-check:
    name: flake self-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@v5
      with:
        fail-mode: true

  pre-commit-check:
    name: workspace pre-commit check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: run pre-commit check
      run: nix develop .#lint -c ./misc/git-hooks/pre-commit

  run-build-workflow:
    name: build
    needs: pre-commit-check
    uses: ./.github/workflows/build.yml
